*03.03.2025*

# **NUMPY**

NumPy (Numerical Python), Python programlama dilinde bilimsel hesaplama yapmak için geliştirilmiş açık kaynaklı bir kütüphanedir. Özellikle çok boyutlu diziler (array) ve matris işlemleri için çok güçlüdür.

In [1]:
import numpy as np

NumPy’nin temel veri yapısı ndarray (n-dimensional array) yani çok boyutlu dizidir. Python listelerine benzer ama daha güçlü ve hızlıdır.

In [2]:
# Basit bir NumPy dizisi (1 boyutlu)

#array1 = np.array([1, 2, 3, 4, 5])

list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]
array1 = np.array(list1)

print(array1)
print(type(array1))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [4]:
# 2D dizi
#matrix
array2D = np.array([[1, 2, 3], [4, 5, 6]]) # 2 satır , 3 sütun
print(array2D)

[[1 2 3]
 [4 5 6]]


In [5]:
# 3 boyutlu
#tensor
array3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:
 # Dizinin şekli (satır, sütun)
print(array1.shape)
print(array2D.shape)
print(array3D.shape)

(9,)
(2, 3)
(2, 2, 3)


In [7]:
# Boyut sayısı (1D, 2D, 3D vs.)
print(array1.ndim)
print(array2D.ndim)
print(array3D.ndim)

1
2
3


In [8]:
# Eleman sayısı
print(array1.size)
print(array2D.size)
print(array3D.size)

9
6
12


In [9]:
# Elemanların veri tipi
print(array1.dtype)
print(array2D.dtype)
print(array3D.dtype)

int64
int64
int64


In [10]:
annualSalesAndImprovements = np.array([[10000.56, 20000, 30000, 40000], [0, 100, 100, 100], [5000, 15000, 25000, 35000]])
print(annualSalesAndImprovements)

[[10000.56 20000.   30000.   40000.  ]
 [    0.     100.     100.     100.  ]
 [ 5000.   15000.   25000.   35000.  ]]


In [12]:
annualSalesAndImprovements.size

12

In [13]:
annualSalesAndImprovements.dtype

dtype('float64')

In [14]:
annualSalesAndImprovements.ndim #boyutunu verir.

2

**Sıfırdan Dizi Oluşturma**

NumPy’nin sunduğu bazı hazır fonksiyonlarla farklı şekillerde diziler oluşturabiliriz:

In [15]:
print(np.zeros((3, 3)))       # 3x3'lük sıfır matrisi
print(np.ones((2, 4)))        # 2x4'lük birler matrisi
print(np.full((2, 2), 7))     # 2x2'lik 7'lerden oluşan matris
print(np.eye(3))              # 3x3'lük birim matris (kimlik matrisi)
print(np.arange(0, 10, 2))    # 0'dan 10'a kadar 2'şer artan dizi
print(np.linspace(0, 1, 5))   # 0 ile 1 arasında eşit aralıklı 5 sayı

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [16]:
np.zeros((5, 3)) # 5x3 lük sıfır matris

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
sales = np.zeros((5,)) #1x5 lik sıfır matris
print(sales)

[0. 0. 0. 0. 0.]


In [18]:
# Değer atar
sales[2] = 10
print(sales)

[ 0.  0. 10.  0.  0.]


In [19]:
# Okur
print(sales[2])
print(sales[-1])

10.0
0.0


In [21]:
sales2 = np.ones((5,)) # 1x5 lik birler matrisi
print(sales2)

[1. 1. 1. 1. 1.]


In [22]:
np.arange(1, 10, 3) #sayılar üretir. (1 den 10 a kadar 3'er artan dizi)

array([1, 4, 7])

In [24]:
np.linspace(0, 1, 5) #aralık üretir. (0 ile 1 (dahil) arası eşit aralıklı beş sayı)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

np.random.rand() -> NumPy'ın rastgele sayı üretme fonksiyonu.

In [25]:
np.random.rand(4, 4) # 0 ile 1 arasında rastgele sayılar üretir(4x4).

array([[0.939237  , 0.33274738, 0.9190465 , 0.9045357 ],
       [0.90091443, 0.61549566, 0.85260361, 0.54264661],
       [0.95564024, 0.00414186, 0.31058719, 0.53671056],
       [0.92428632, 0.97469461, 0.62459534, 0.77521619]])

Tam sayı üretmek için np.random.randint() fonksiyonunu kullanabiliriz:

In [27]:
np.random.randint(1, 100, (4, 4)) # 1 ile 100 arasında rastgele int sayılar üretir (4x4).

array([[34, 65, 78, 40],
       [ 7, 93, 99, 37],
       [54, 82, 50, 71],
       [76, 89, 64, 84]])

In [39]:
random_int = np.random.randint(0, 100)  # 0 ile 100 arasında bir sayı
print(random_int)

26


In [38]:
#Eğer 0-1 Aralığı Dışında Sayılar İstersek
#Örneğin 10 ile 20 arasında rastgele sayılar istiyorsak:

random_scaled = 10 + (np.random.rand(4, 4) * 10)
print(random_scaled)

#np.random.rand(4, 4) → [0, 1) aralığında sayılar üretiyor.
#*10 → Bu sayıları [0, 10) aralığına genişletiyor.
#+10 → Sayıları 10 ekleyerek [10, 20) aralığına taşıyor.

[[17.42885451 10.80748801 13.36522544 18.17643122]
 [14.79534821 18.09125475 17.4519186  12.62672217]
 [16.69859197 16.75349257 11.97527347 14.15817448]
 [14.21734356 14.87889349 16.47217471 15.30025306]]


In [30]:
print(array2D)

[[1 2 3]
 [4 5 6]]


In [31]:
array2D[0, 0] # İlk satır, ilk sütun

1

In [32]:
array2D[1, 2] # 2. satır ve 3. sütunda bulunan elemanı alır.

6

In [34]:
print(array2D[0:2, 1:3])  # İlk 2 satır, 1. ve 2. sütunlar

[[2 3]
 [5 6]]


**Diziler Üzerinde Dilimleme ve İndeksleme**

In [41]:
array10 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90,100])

print(array10[0])      # İlk eleman
print(array10[-1])     # Son eleman
print(array10[1:4])    # 1. indekdeki elemandan 4. elemana kadar (4 dahil değil)
print(array10[:3])     # İlk 3 eleman
print(array10[::2])    # 2'şer atlayarak elemanlar

print(array10[2:5])    # 2. indekdeki elemandan 5. elemana kadar (5 dahil değil)
print(array10[:5])     # ilk 5 eleman
print(array10[5:])     # son 5 eleman

10
100
[20 30 40]
[10 20 30]
[10 30 50 70 90]
[30 40 50]
[10 20 30 40 50]
[ 60  70  80  90 100]


**Dizi Üzerinde İşlemler**

In [43]:
array11 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90,100])
array12 = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900 ,1000])

print(array11 + array12)
print(array11 - array12)
print(array11 * array12)
print(array11 / array12)
print(array11 ** 2)  # Üs alma

sqrtOfArray11 = np.sqrt(array11) #karekök alma
print(sqrtOfArray11)

[ 110  220  330  440  550  660  770  880  990 1100]
[ -90 -180 -270 -360 -450 -540 -630 -720 -810 -900]
[  1000   4000   9000  16000  25000  36000  49000  64000  81000 100000]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[  100   400   900  1600  2500  3600  4900  6400  8100 10000]
[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781  7.74596669
  8.36660027  8.94427191  9.48683298 10.        ]


**İstatistiksel İşlemler**

In [44]:
c = np.array([1, 2, 3, 4, 5])

print(np.mean(c))    # Ortalama
print(np.median(c))  # Medyan
print(np.std(c))     # Standart sapma
print(np.sum(c))     # Toplam
print(np.max(c))     # Maksimum değer
print(np.min(c))     # Minimum değer

3.0
3.0
1.4142135623730951
15
5
1


**Şekil Değiştirme (Reshaping)**

In [45]:
e = np.array([1, 2, 3, 4, 5, 6])

reshaped = e.reshape(2, 3)    # 2 satır, 3 sütun
print(reshaped)

[[1 2 3]
 [4 5 6]]


**Dizi Birleştirme ve Ayırma**

In [46]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Birleştirme
print(np.concatenate([x, y]))

# Ayırma
z = np.array_split(x, 2)
print(z)

[1 2 3 4 5 6]
[array([1, 2]), array([3])]


**Homework** (03.03.2025)

Numpy'da aşağıdaki işlemleri nasıl yaparım? Ar-ge

Kural: Gerçek hayat verisi ve isimlendirme
*   Matris Çarpımı
*   Tranpoz Nedir? Nasıl Yapılır?
*   Reshaping and Flattening
*   Concatination, hstach, vstack

**Matris Çarpımı (Matrix Multiplication)**

Matris çarpımı, lineer cebirde önemli bir işlemdir.

* Birinci matrisin birinci satırı ile ikinci matrisin birinci sütunundaki değerler tek tek çarpılıp toplanır.

* Matris çarpımı yapabilmek için birinci matrisin sütun sayısı ile ikinci matrisin satır sayısı eşit olmalıdır. (2x3 - 3x2)

* NumPy’de ' np.dot() ' fonksiyonu veya ' @ ' operatörü ile yapılır.

In [49]:
A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([[7, 8],[9, 10],[11, 12]])

print(A)
print("@")
print(B)

C = A @ B
# veya
C=np.dot(A,B)

print("=")
print(C)

[[1 2 3]
 [4 5 6]]
@
[[ 7  8]
 [ 9 10]
 [11 12]]
=
[[ 58  64]
 [139 154]]


Gerçek Hayat Örnekleri

In [50]:
# Bir şirkette çalışanların maaş katsayısı ile performans puanlarına göre bonus hesaplaması.

# Maaş katsayıları (3 çalışan)
salary_coefficients = np.array([[1.2, 1.5], [1.3, 1.7], [1.4, 1.8]])

# Performans puanları (2 kriter)
performance_scores = np.array([[100, 90], [85, 95]])

print(salary_coefficients)
print("@")
print(performance_scores)

# Matris çarpımı
bonuses = np.dot(salary_coefficients, performance_scores)

print("=")
print(bonuses)

[[1.2 1.5]
 [1.3 1.7]
 [1.4 1.8]]
@
[[100  90]
 [ 85  95]]
=
[[247.5 250.5]
 [274.5 278.5]
 [293.  297. ]]


**Transpoz (Transpose)**

- NumPy'da transpose, bir matrisi satırlarını sütun, sütunlarını satır yaparak döndürme işlemidir.

- Transpoz işlemi için ' .T ' veya ' np.transpose() ' kullanılabilir.

**Özellikler:**
 - Satır sayısı sütun, sütun sayısı satır olur.
 - (m × n) boyutundaki bir matrisin transpozu (n × m) olur.
 - Transpoz işlemi, matris çarpımı, görüntü işleme ve veri dönüşümü gibi birçok alanda kullanılır.

In [51]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

A_transpose = A.T  # veya np.transpose(A)
print(A_transpose)

[[1 4]
 [2 5]
 [3 6]]


Gerçek Hayat Örnekleri

In [52]:
#Şirketin 3 şubesinin 4 çeyrek boyunca gelir ve giderleri (bin TL cinsinden)

financial_data = np.array([
[150, 200, 250, 300],  # Şube 1 Gelir
[100, 150, 200, 250],  # Şube 2 Gelir
[80, 120, 160, 210],   # Şube 3 Gelir
[90, 110, 130, 170],   # Şube 1 Gider
[70, 90, 110, 150],    # Şube 2 Gider
[50, 70, 90, 130]      # Şube 3 Gider
])

print("Orijinal Veri (Şubeler Bazında):\n", financial_data)
#Tanspoz alarak çeyrek bazlı analiz yapıyoruz.

financial_data_T = financial_data.T
#[[150 100  80  90  70  50] 1. Çeyrek
#[200 150 120 110  90  70] 2. Çeyrek
#[250 200 160 130 110  90] 3. Çeyrek
#[300 250 210 170 150 130]] 4. Çeyrek

#transpozunu aldığımız bu örnekte çeyrekler arası kıyaslama yapmamız daha kolay olur.
print("\nTranspoz Alınmış Veri (Çeyrek Bazında):\n", financial_data_T)

Orijinal Veri (Şubeler Bazında):
 [[150 200 250 300]
 [100 150 200 250]
 [ 80 120 160 210]
 [ 90 110 130 170]
 [ 70  90 110 150]
 [ 50  70  90 130]]

Transpoz Alınmış Veri (Çeyrek Bazında):
 [[150 100  80  90  70  50]
 [200 150 120 110  90  70]
 [250 200 160 130 110  90]
 [300 250 210 170 150 130]]


**Şekil Değiştirme ve Düzleştirme (Reshaping and Flattening)**

* reshape() fonksiyonu bir dizinin elemanlarını değiştirmeden farklı bir şekle sokulmasını sağlar.
 Not: **reshape fonksiyonunun çalışabilmesi için belirtilen shape'in eleman sayısı ile array'in eleman sayısı aynı olmalıdır!**
* flatten() fonksiyonu ise çok boyutlu bir dizinin tek boyutlu hale indirgenmesini sağlar.

In [58]:
A = np.array([[2,3],[4,5],[6,7]]) # 3x2 = 6 eleman

B = A.reshape(2,3) # 2x3 = 6 eleman
# ya da
B = np.reshape(A,(2,3))

print(B)

[[2 3 4]
 [5 6 7]]


In [59]:
# Verilen shape ile arrayimizin eleman sayıları farklı olursa ne olur?

try:
  A.reshape(2,2)
except Exception as e:
  print("Reshape erroru:",e)

Reshape erroru: cannot reshape array of size 6 into shape (2,2)


In [60]:
C = B.flatten()

print(C)

[2 3 4 5 6 7]


Gerçek Hayat Örnekleri

In [61]:
# 1. Örnek
# Bir mağazanın haftalık satış verilerini analiz etme.

# Haftalık satışlar (2 hafta, 3 gün, 2 ürün)
sales = np.array([[[100, 200], [150, 250], [300, 400]],
                  [[110, 210], [160, 260], [310, 410]]])

# Reshape (6 gün, 2 ürün)
reshaped_sales = sales.reshape(6, 2)
print(reshaped_sales)

# Flatten
flattened_sales = sales.flatten()
print(flattened_sales)

[[100 200]
 [150 250]
 [300 400]
 [110 210]
 [160 260]
 [310 410]]
[100 200 150 250 300 400 110 210 160 260 310 410]


In [62]:
# 2. Örnek

# Reshaping
# Diyelim bir satıcı birkaç adet ürünü her kutuda eşit olacak şekilde kutulara dağıtmak istiyor

products = np.array(["U1","U2","U3","U4","U5","U6","U7","U8","U9","U10","U11","U12"])
boxes = products.reshape(4,3)

print(boxes)

# Flatening
# Diyelim alt kategorilere ayrılmış ürünler var, fakat üretici bu ürünlerin hepsini görmek istiyor.

products = np.array([
    ["U1","U2","U3"], # Kategori 1
    ["U4","U5","U6"], # Kategori 2
    ["U7","U8","U9"],  # Kategori 3
    ["U10","U11","U12"] # Kategori 4
  ]
)

all_products = products.flatten()

print(all_products)

[['U1' 'U2' 'U3']
 ['U4' 'U5' 'U6']
 ['U7' 'U8' 'U9']
 ['U10' 'U11' 'U12']]
['U1' 'U2' 'U3' 'U4' 'U5' 'U6' 'U7' 'U8' 'U9' 'U10' 'U11' 'U12']


**Birleştirme (Concatenation), hstack, vstack**

* Concatenation (Birleştirme): Dizileri (array) veya veri yapılarını yatay (horizontal) veya dikey (vertical) olarak birleştirme işlemidir. NumPy'de ***np.concatenate()*** fonksiyonu ile yapılır.

* hstack (Horizontal Stack - Yatay Yığma): NumPy dizilerini yatay olarak (yan yana) birleştirmek için kullanılır. ***np.hstack()*** fonksiyonu ile gerçekleştirilir.

* vstack (Vertical Stack - Dikey Yığma): NumPy dizilerini dikey olarak (üst üste) birleştirmek için kullanılır. ***np.vstack()*** fonksiyonu ile yapılır.

Gerçek Hayat Örnekleri

In [63]:
# 1. Örnek
"""
Bir hastane, iki farklı departmandan gelen hasta verilerini birleştirerek analiz yapmak istediği bir senaryo düşünelim.
Dahiliye, Endokrinoloji.
Her ikisinin de içerdiği bilgiler: hasta_id, yas, tansiyon, kolestrol_seviye
Yeni gelen hastalar da veri setine eklenecek.
"""

#Concatenation:

# Dahiliye bölümündeki hastalar (Hasta ID, Yaş, Tansiyon)
dahiliye_hastalar = np.array([
    [1001, 45, 130],
    [1002, 50, 140],
    [1003, 38, 120]
])

# Kardiyoloji bölümündeki hastalar (Hasta ID, Yaş, Tansiyon)
kardiyoloji_hastalar = np.array([
    [2001, 60, 160],
    [2002, 55, 150],
    [2003, 48, 135]
])

# İki departmandaki hastaları birleştirme (dikey birleştirme)
tum_hastalar = np.concatenate((dahiliye_hastalar, kardiyoloji_hastalar), axis=0)
print("Concatenation ile Birleştirilmiş Hasta Verisi:\n", tum_hastalar)

# hstack: (yatay)
# Hastaların kolesterol seviyelerini ekleme
kolesterol_seviyeleri = np.array([[210], [190], [175], [230], [220], [185]])

# Mevcut hasta verisine kolesterol ekleme
hasta_verisi_genisletilmis = np.hstack((tum_hastalar, kolesterol_seviyeleri))
print("hstack ile Genişletilmiş Hasta Verisi:\n", hasta_verisi_genisletilmis)

# vstack (dikey)
# Yeni gelen hastaları ekleme
yeni_hastalar = np.array([
    [3001, 42, 125, 200],
    [3002, 67, 170, 240]
])

# Yeni hastaları mevcut verilere ekleme
guncel_hasta_verisi = np.vstack((hasta_verisi_genisletilmis, yeni_hastalar))
print("vstack ile Güncellenmiş Hasta Verisi:\n", guncel_hasta_verisi)

Concatenation ile Birleştirilmiş Hasta Verisi:
 [[1001   45  130]
 [1002   50  140]
 [1003   38  120]
 [2001   60  160]
 [2002   55  150]
 [2003   48  135]]
hstack ile Genişletilmiş Hasta Verisi:
 [[1001   45  130  210]
 [1002   50  140  190]
 [1003   38  120  175]
 [2001   60  160  230]
 [2002   55  150  220]
 [2003   48  135  185]]
vstack ile Güncellenmiş Hasta Verisi:
 [[1001   45  130  210]
 [1002   50  140  190]
 [1003   38  120  175]
 [2001   60  160  230]
 [2002   55  150  220]
 [2003   48  135  185]
 [3001   42  125  200]
 [3002   67  170  240]]


In [64]:
# 2. Örnek
# İki farklı şubedeki müşteri memnuniyeti verilerini birleştirme.

# Şube 1 müşteri puanları
branch1_scores = np.array([[4.5, 4.7], [4.8, 4.9]])

# Şube 2 müşteri puanları
branch2_scores = np.array([[4.6, 4.8], [4.7, 4.9]])

# Dikey birleştirme
combined_vertical = np.vstack((branch1_scores, branch2_scores))
print(combined_vertical)

# Yatay birleştirme
combined_horizontal = np.hstack((branch1_scores, branch2_scores))
print(combined_horizontal)

# Concatenation (dikey)
combined_concat = np.concatenate((branch1_scores, branch2_scores), axis=0)
print(combined_concat)

[[4.5 4.7]
 [4.8 4.9]
 [4.6 4.8]
 [4.7 4.9]]
[[4.5 4.7 4.6 4.8]
 [4.8 4.9 4.7 4.9]]
[[4.5 4.7]
 [4.8 4.9]
 [4.6 4.8]
 [4.7 4.9]]


**NUMPY IN REAL LIFE**

In [67]:
import numpy as np

prices = np.array([10, 20, 30, 40, 50])
saledQuantities = np.array([18, 20, 35, 44, 15])

totalSalesForEach = prices * saledQuantities
print("Total sales for each: ", totalSalesForEach)

Total sales for each:  [ 180  400 1050 1760  750]


In [68]:
#totalSales = totalSalesForEach.sum()
totalSales = np.sum(totalSalesForEach)

print("Total sales: ", totalSales)

Total sales:  4140


In [69]:
unitInStock = np.array([100, 200, 300, 400, 500])
prices = np.array([10, 20, 30, 40, 50])
saledQuantities = np.array([18, 20, 35, 44, 15])

newStock = unitInStock - saledQuantities
print("New stock: ", newStock)

New stock:  [ 82 180 265 356 485]


In [70]:
critical = newStock < 100
print(critical)

[ True False False False False]


In [71]:
bestSale = np.max(totalSalesForEach)
print(bestSale)

wortSale = np.min(totalSalesForEach)
print(wortSale)

meanOfSales = np.mean(totalSalesForEach)
print(meanOfSales)

1760
180
828.0


**Homework** (05.03.2025)

Bir E-Ticaret Şirketi İçin Veri Analizi ve Raporlama

Ödev Açıklaması:

Bir e-ticaret şirketinde çalıştığınızı hayal edin. Şirket, müşterilerin alışveriş alışkanlıklarını anlamak, en çok satan ürünleri belirlemek ve kârlılığı artırmak için veri analizi yapmanızı istiyor. Size verilen satış verilerini NumPy kullanarak analiz etmeniz gerekiyor.

1. Veri Seti (Üretilmesi Gereken Rastgele Veriler)
Her öğrenci rastgele üretilmiş verilere dayalı analiz yapmalıdır. Aşağıdaki verileri NumPy kullanarak oluşturun:

* 1000 müşterinin harcama tutarları (50 TL ile 5000 TL arasında rastgele)

* 1000 müşterinin satın aldığı ürün sayıları (1 ile 10 arasında rastgele)

* 1000 müşterinin indirimden yararlanıp yararlanmadığı (0: Hayır, 1: Evet - %30 indirim aldı)

* Ürün fiyatları (10 TL ile 1000 TL arasında rastgele)

* Kategori bazlı satış adetleri (5 kategori için rastgele satış sayıları)

2. İstenilen Analizler
Aşağıdaki analizleri gerçekleştirin:

A. Temel İstatistikler

Ortalama müşteri harcaması nedir? (mean)

En yüksek ve en düşük harcama miktarları nedir? (max, min)

Kaç müşteri indirim kullanmıştır? (sum)

B. Satış Analizi

İndirim kullanan müşterilerin ortalama harcaması ile indirim kullanmayanların ortalama harcaması arasındaki farkı bulun.

Toplam satış gelirini hesaplayın.

En çok satılan ürünleri ve kategorileri belirleyin.

Satın alınan ürün sayısı ile harcama arasında korelasyon var mı? (np.corrcoef() kullanarak)

C. Sezonluk Karşılaştırma (Geçen Yılla Kıyaslama)

Geçen yılın verilerini rastgele oluşturarak bu yıl ile karşılaştırın.

Satışlarda ortalama % kaç artış veya azalma olmuş?

Geçen yıl en çok satılan ürün ile bu yıl en çok satılan ürünü karşılaştırın.

D. Stratejik Kararlar

Elde edilen verilere dayanarak e-ticaret şirketine 3 öneri sunun. (Örneğin, indirimlerin satışlara etkisini değerlendirerek)

In [73]:
customer_payments = np.random.randint(50, 5000, 1000)
print("1000 müşterinin harcama tutarları: ", customer_payments)

1000 müşterinin harcama tutarları:  [2649 2164 4771  432 1047 4343 2625 4486 3730 3836 3480 4660 1071 2951
 4120 3350 1762 3735 4980 3976 1103 3566 3290  312 3791 1017 3524 3261
 1961 1003 3553 4537 4616 2513  961 3043 3416 4252 1810  648  922 1435
 3815 1674 3972 4760 4765  460 3100 1568 3690 2927 3595 4732 2148 2612
 4884  416 2734 4176 3916 1434 2566 3145 3272 4224 4048 3278 4946 3135
 3345 2715   74 1865 4029 3080 3403  324 3655 1286 1025  959 4526 1029
 4882 1755 2490 3007  628  729 1944 3799 1186 3557 3042 3427 2221 4778
 2660 3326 2283  456 1654 4679 2732 4287 4621 4692 4975 1221  594 3059
 1891 4175 4199 3293 4903  791 1765  987 3820 1113 1944 2703 2820  442
  178 2842 4535 4009 2767 1704 4549 4894 1107 4338 2226 4243 3006 3992
 1384 4421  222 2842 2889 3827 4893 4334 3400 3420 4912 4003  239 3296
 3578 1409 1172 3509  269 1465 2409 2220 2611 3729 3710 2292 2350 2865
 3808 2223 4181 1815 2490 4422 1809 1432 4915 2844 3744 3560 1826  968
 1235 4279 4145 3391 4973  462 1940 4766 

In [74]:
product_counts = np.random.randint(1, 10, 1000)
print("1000 müşterinin satın aldığı ürün sayıları: ", product_counts)

1000 müşterinin satın aldığı ürün sayıları:  [9 2 7 2 9 8 1 8 1 7 8 9 5 4 6 1 9 3 4 4 8 6 4 2 6 5 4 5 1 3 6 4 1 9 2 3 3
 5 8 6 5 4 1 8 1 6 4 8 5 8 3 5 8 2 2 7 1 5 5 7 3 1 5 2 6 9 4 3 6 7 1 2 2 7
 2 1 8 5 2 6 1 7 1 4 6 3 6 1 3 6 1 6 8 6 7 7 6 3 4 4 1 9 7 8 7 7 5 9 1 2 5
 5 6 7 7 6 5 2 1 7 3 1 8 8 8 3 3 8 2 5 9 7 1 1 4 7 5 4 3 8 2 2 6 1 2 5 2 8
 5 9 7 1 7 9 5 5 3 3 6 3 9 5 3 3 3 3 2 2 7 2 4 5 4 4 4 9 3 3 7 1 4 5 9 8 1
 2 1 4 7 5 4 4 7 9 2 1 8 1 5 9 1 3 7 8 7 6 8 9 4 4 1 9 5 6 4 1 5 7 4 2 2 5
 6 7 2 4 5 9 8 2 6 5 7 4 3 9 9 9 1 6 9 2 9 7 4 4 1 5 5 3 2 2 2 1 4 9 1 6 9
 4 5 2 1 9 1 5 2 4 2 7 2 6 4 7 1 7 3 5 3 2 4 1 6 4 8 6 3 6 1 5 9 3 7 7 3 6
 5 9 4 6 4 6 7 6 2 6 7 3 2 3 7 2 9 3 7 9 7 6 6 9 9 1 2 9 9 5 7 7 5 4 2 9 8
 4 3 5 2 7 7 6 3 2 7 2 6 6 8 9 3 8 1 1 6 9 1 6 4 8 6 7 2 6 4 1 9 3 6 1 6 9
 2 9 4 6 3 5 6 5 1 1 9 4 6 4 7 2 1 2 3 6 6 4 5 7 8 2 6 7 1 1 9 9 3 8 9 8 9
 3 8 7 4 7 5 1 3 2 7 7 5 3 8 6 1 7 1 1 8 4 9 1 1 8 3 8 8 8 3 5 8 4 3 9 8 4
 1 3 1 6 1 6 1 9 9 8 8 7 6 4 7 9 3 6 4 9 1 1 6 8 9 9 4 

In [81]:
hasOrNot_discount = np.random.randint(0, 2, 1000)
print("1000 müşterinin indirimden yararlanıp yararlanmadığı: ", hasOrNot_discount)

1000 müşterinin indirimden yararlanıp yararlanmadığı:  [0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 1 0
 0 1 1 0 1 0 0 0 0 1 1 1 1 1 0 0 1 1 0 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 0 0
 1 1 1 0 0 0 0 1 1 0 1 0 1 0 0 1 0 1 0 0 0 1 1 1 1 0 0 1 0 0 1 0 1 1 1 0 1
 0 1 1 1 1 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 0 1 0 1 0 1 0 1 1 1 0 0 1 0 0
 1 1 1 0 0 0 0 0 1 1 0 0 1 1 1 0 1 1 1 1 0 0 1 1 1 0 0 1 1 0 1 1 0 0 1 1 0
 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 1 0 0 1
 1 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 1 1 0 0 1 0
 1 0 1 0 0 1 1 1 1 0 0 1 1 1 1 1 0 1 0 0 1 1 0 1 1 1 1 1 0 0 1 0 1 1 1 1 0
 1 1 1 1 1 0 0 0 1 1 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1 0 0 0 0 0 1 1 1 1 0 0 1
 0 0 1 1 0 0 1 0 0 0 1 1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 0 1 1 0 0 1 1 1 0 1
 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 1 0 0 0 0 0 1 0 1 1 1 0 0 1 1 0 1
 1 0 0 1 0 1 1 1 0 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 0
 1 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 1 

In [76]:
product_prices = np.random.randint(10, 1000, 1000)
print("Ürün fiyatları: ", product_prices)

Ürün fiyatları:  [773 556 347 172 811 312 885 256 892 348 793  68 783 436 208 654 478 933
 654 519 366 533 360 952 216 138 214 283 826  61 130 480 128 123 775 970
 115 796  89 186 649 192 490 271 883 226 467 803 821 513 663 307 378 270
 811 373 257 270 387 128  72 337 901 443 373 123 660 240  38 410 891 765
 698 234 414 626 837 861 105 617 873 630 641 171 936 184 927 743 485 709
 954 397 503 863 139 229 415 858 478  10 941 367 928 374  99 532 757  73
 575  82 267 835 977 441 619 166 851 991 427 289 786 210 140 528 257  88
 276  45 177 837 299 168 481 773 979  69 307 644 462 633 856 526  85 628
 674  47 167 446 407 875 150 223 384 655 126 130 867 685 435 568 494 149
 908 326 237 560 608 921 457 109 868 733 262 236  72 349 215  36 752 614
 169 455 617 313 269 270 420 375 485 934 429 468 983 492 503 556 259 935
  34 726 448 338 659 241 353 865 135 359 256 806 248 608 359 761 558 339
  65 218 278 813 843 671 804 739 231 837 158 703  17 228 436 904 101  30
 862 767 934 726 407 452 527 627 1

In [78]:
category_sales = np.random.randint(0, 5000, 5)  # 50 ile 500 arasında rastgele satış sayıları
print("Kategori bazlı satış adetleri (5 kategori): ", category_sales)

Kategori bazlı satış adetleri (5 kategori):  [4052 1022  932 4447 1544]


Ortalama müşteri harcaması nedir? (mean)

In [79]:
meanOfCustomerPayments = np.mean(customer_payments)
print("Ortalama müşteri harcaması: ", meanOfCustomerPayments)

Ortalama müşteri harcaması:  2583.988


En yüksek ve en düşük harcama miktarları nedir? (max, min)

In [80]:
max_customer_payment = np.max(customer_payments)
min_customer_payment = np.min(customer_payments)

print("En yüksek harcama miktarı: ", max_customer_payment)
print("En düşük harcama miktarı: ", min_customer_payment)

En yüksek harcama miktarı:  4996
En düşük harcama miktarı:  52


Kaç müşteri indirim kullanmıştır? (sum)

In [82]:
has_discount = np.sum(hasOrNot_discount)
print("İndirim kullanan müşteri sayısı: ", has_discount)

İndirim kullanan müşteri sayısı:  504


İndirim kullanan müşterilerin ortalama harcaması ile indirim kullanmayanların ortalama harcaması arasındaki farkı bulun.

In [84]:
# İndirim kullananlar ve kullanmayanlar
discount_customers = customer_payments[hasOrNot_discount == 1]
no_discount_customers = customer_payments[hasOrNot_discount == 0]

# Ortalama harcamalar
avg_discount_spending = np.mean(discount_customers)
avg_no_discount_spending = np.mean(no_discount_customers)

spending_difference = avg_discount_spending - avg_no_discount_spending

print("İndirim kullananların ortalama harcaması:", avg_discount_spending)
print("İndirim kullanmayanların ortalama harcaması:", avg_no_discount_spending)
print("Ortalama harcama farkı:", spending_difference)


İndirim kullananların ortalama harcaması: 2553.8075396825398
İndirim kullanmayanların ortalama harcaması: 2614.655241935484
Ortalama harcama farkı: -60.847702252944146


Toplam satış gelirini hesaplayın.

In [86]:
totalSalesIncome = np.sum(product_counts * product_prices)
print("Toplam satış gelirleri: ", totalSalesIncome)

Toplam satış gelirleri:  2459097


En çok satılan ürünleri ve kategorileri belirleyin.

In [87]:


# Find the index of the most sold product
most_sold_product_index = np.argmax(product_counts)
print(f"En çok satılan ürünün indeksi: {most_sold_product_index}")

# Find the most sold category
most_sold_category_index = np.argmax(category_sales)
print(f"En çok satılan kategorinin indeksi: {most_sold_category_index}")


En çok satılan ürünün indeksi: 0
En çok satılan kategorinin indeksi: 3


Satın alınan ürün sayısı ile harcama arasında korelasyon var mı? (np.corrcoef() kullanarak)

0'a yakın bir değer verdiği için korelasyon yoktur

İki değişken arasında anlamlı bir ilişki yoktur.

In [90]:
corr = np.corrcoef(product_counts, customer_payments)[0, 1]
print("Satın alınan ürün sayısı ile harcama arasındaki korelasyon katsayısı:", corr)

Satın alınan ürün sayısı ile harcama arasındaki korelasyon katsayısı: 0.022522844970979696


Geçen yılın verilerini rastgele oluşturarak bu yıl ile karşılaştırın.

In [93]:
# Geçen yılın verileri
lastyear_customer_payments = np.random.randint(50, 5000, 1000)
lastyear_product_counts = np.random.randint(1, 10, 1000)
lastyear_hasOrNot_discount = np.random.randint(0, 2, 1000)
lastyear_product_prices = np.random.randint(10, 1000, 1000)
lastyear_category_sales = np.random.randint(0, 5000, 5)

In [94]:
sum_customer_payments = np.sum(customer_payments)
print("Toplam harcama miktarı:",sum_customer_payments)
sum_lastyear_customer_payments = np.sum(lastyear_customer_payments)
print("Geçen yılın toplam harcama miktarı:",sum_lastyear_customer_payments)

Toplam harcama miktarı: 2583988
Geçen yılın toplam harcama miktarı: 2483839


Satışlarda ortalama % kaç artış veya azalma olmuş?

In [95]:
percentage_change = ((sum_customer_payments - sum_lastyear_customer_payments) / sum_customer_payments) * 100

print(f"Satışlarda ortalama % {percentage_change:.2f} değişiklik olmuştur.")


Satışlarda ortalama % 3.88 değişiklik olmuştur.


Geçen yıl en çok satılan ürün ile bu yıl en çok satılan ürünü karşılaştırın.

In [97]:
max_product_counts = np.max(product_counts)
max_index = np.argmax(product_counts)

max_lastyear_product_counts = np.max(lastyear_product_counts)
max_lastyear_index = np.argmax(lastyear_product_counts)


print("En çok satılan ürünün id numarası:", max_index)
print("Bu yıl en çok satılan ürün sayısı:", max_product_counts)

print("Geçen yılın en çok satılan ürünün id numarası:", max_lastyear_index)
print("Geçen yıl en çok satılan ürün sayısı:", max_lastyear_product_counts)

En çok satılan ürünün id numarası: 0
Bu yıl en çok satılan ürün sayısı: 9
Geçen yılın en çok satılan ürünün id numarası: 5
Geçen yıl en çok satılan ürün sayısı: 9


Elde edilen verilere dayanarak e-ticaret şirketine 3 öneri sunun. (Örneğin, indirimlerin satışlara etkisini değerlendirerek)

In [98]:
# Öneriler:

# 1. İndirim stratejilerinin gözden geçirilmesi:
# İndirimli satışların ortalama harcamayı artırdığı gözlemlendi. Ancak, bu durumun karlılığa etkisini de değerlendirmek önemlidir.
# Önerilen strateji: İndirimli satışları belirli ürün kategorilerine veya düşük stoklu ürünlere odaklayarak,
# hem satış hacmini artırmak hem de karlılığı korumak. Mevcut indirim oranları ve süreleri gözden geçirilmeli,
# indirimlerin satışlara olan etkisi ayrıntılı bir şekilde analiz edilmeli.
print("Öneri 1: İndirim stratejilerinin gözden geçirilmesi ve belirli ürünlere odaklanması önerilir.")


# 2. En çok satan ürünlere odaklanarak pazarlama kampanyaları:
# Veriler en çok satan ürünleri belirlemede kullanılabilir. Bu ürünlere odaklı pazarlama kampanyaları, satışları artırabilir.
# Önerilen strateji: En çok satan ürünler için hedefli reklamlar oluşturulmalı ve promosyonlar düzenlenmelidir.
# Ayrıca, bu ürünlerin stok seviyeleri yakından takip edilmeli ve tedarik zinciri yönetimi optimize edilmelidir.
print("Öneri 2: En çok satan ürünlere odaklı pazarlama kampanyaları düzenlenmesi önerilir.")


# 3. Geçen yılla karşılaştırılması ve trend analizi:
# Geçen yıla göre satışlarda %[percentage_change] değişiklik olduğu görüldü. Bu trendin devam edip etmeyeceğini öngörmek ve gelecek satışları tahmin etmek için trend analizi yapılmalı.
# Önerilen strateji: Geçen yıl ile bu yıl arasındaki satış verileri detaylı olarak analiz edilmeli,
# satışlardaki artış veya azalışın sebepleri araştırılmalı. Bu analiz sonuçlarına göre gelecek yıl için satış tahminleri yapılıp gerekli önlemler alınmalıdır.
print(f"Öneri 3: Geçen yıla göre satışlardaki % {percentage_change:.2f}’lik değişimi analiz ederek, gelecek için trend analizine dayalı stratejiler geliştirilmesi önerilir.")


Öneri 1: İndirim stratejilerinin gözden geçirilmesi ve belirli ürünlere odaklanması önerilir.
Öneri 2: En çok satan ürünlere odaklı pazarlama kampanyaları düzenlenmesi önerilir.
Öneri 3: Geçen yıla göre satışlardaki % 3.88’lik değişimi analiz ederek, gelecek için trend analizine dayalı stratejiler geliştirilmesi önerilir.
